# Generated by Django 3.2.7 on 2021-09-25 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_num', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the form of +919999999999.', regex='^\\+?1?\\d{9,14}$')])),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(max_length=5000)),
            ],
        ),
    ]
